# Bitbucket Pipeline file

# This template allows you to validate your PHP application.
# The workflow allows running tests and code linting on the default branch.
image: docker/compose:latest

options:
  docker: true

pipelines:
  branches:
    docker-release:
      - step:
          name: Build
          services:
            - docker
          caches:
            - docker
          runs-on:
            - self.hosted
            - linux
          script:
            # Экспоритруем переменные зашитые в битбакет для развертки
            - echo "Экспоритруем переменные зашитые в битбакет для развертки"
            - echo DB_NAME=$DB_NAME > .env
            - echo DB_USER=$DB_USER >> .env
            - echo DB_PASSWORD=$DB_PASSWORD >> .env
            - echo REDIS_HOST=$REDIS_HOST >> .env
            - echo DB_DSN=$DB_DSN >> .env
            - echo DB_TEST_DSN=$DB_TEST_DSN >> .env
            - echo DB_TEST_CHARSET=$DB_TEST_CHARSET >> .env
            - echo DB_CHARSET=$DB_CHARSET >> .env
            - echo DOMAIN=$DOMAIN >> .env
            - echo DOMAIN_PROTOCOL=$DOMAIN_PROTOCOL >> .env
            - echo DB_TEST_NAME=$DB_TEST_NAME >> .env
            - echo DB_TEST_USER=$DB_TEST_USER >> .env
            - echo DB_TEST_PASSWORD=$DB_TEST_PASSWORD >> .env

            # Смотрим список запущенных сервисов docker-compose
            - docker compose ls

            - echo "Собираем Docker контейнеры"

            # Запускаем контейнеры приложения в фоновом режиме
            - docker-compose up -d

            - echo "Обновляем зависимости composer"

            # Обновляем зависимости композера
            - docker-compose exec -T app composer install --no-interaction

            # Накатываем миграции на dev_eft
            - docker-compose exec -T app php yii migrate --interactive=0

            # Создаем нового юзера MySQL и даем ему все необходимые права, а также создаем новую базу для миграций
            - docker-compose exec -T db mysql -u root -p $DB_PASSWORD
            - use dev_eft;
            - GRANT SUPER ON . to 'prod_user'@'%' WITH GRANT OPTION;
            - GRANT ALL PRIVILEGES ON dev_eft.* to 'prod_user'@'%' WITH GRANT OPTION; (Супер права)
            - CREATE DATABASE test_migrations_db;
            - GRANT SUPER ON . to 'prod_user'@'%' WITH GRANT OPTION;
            - GRANT ALL PRIVILEGES ON test_migrations_db.* to 'prod_user'@'%' WITH GRANT OPTION;
            - quit;

            # Накатываем миграции
            - docker-compose exec -T app php yii migrate --interactive=0

            # todo: Пробуем накатить тут миграции (В bitbucket сейчас dsn_db установлено как db_1 - по умолчанию db)