# Bitbucket Pipeline file

# This template allows you to validate your PHP application.
# The workflow allows running tests and code linting on the default branch.

pipelines:
  branches:
    docker-release:
      - step:
          name: Build
          runs-on:
            - self.hosted
            - linux
          script:
            # Без строк ниже ничего не сработает (В битбакете нету docker-compose по умолчанию, Runner тоже в этом нуждается)
            - export DOCKER_COMPOSE_VERSION=2.4.1
            - export DOCKER_COMPOSE_URL=https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)
            - sudo curl -L $DOCKER_COMPOSE_URL > docker-compose
            - sudo chmod +x docker-compose
            - sudo mv docker-compose /usr/local/bin

            # Экспоритруем переменные зашитые в битбакет для разветки
            - echo DB_NAME=$DB_NAME > .env
            - echo DB_USER=$DB_USER >> .env
            - echo DB_PASSWORD=$DB_PASSWORD >> .env

            - echo "Собираем Docker контейнеры"

            # Запускаем контейнеры приложения в фоновом режиме
            - # sudo docker-compose up -d
            - docker build .

            - echo "Обновляем зависимости composer"

            # Обновляем зависимости композера
            - sudo docker-compose exec -T app composer install --no-interaction