# Bitbucket Pipeline file

# This template allows you to validate your PHP application.
# The workflow allows running tests and code linting on the default branch.

image: docker:stable

options:
  docker: true

pipelines:
  branches:
    docker-release:
      - step:
          name: Install Python and docker
          script:
            # Updating everything
            - sudo apt update
            - sudo apt upgrade -y
            - apt install python3-pip docker
            - pip3 install docker-compose
            - docker-compose -v

      - step:
          name: Build
          script:
            - echo "Build an image with current project via docker"

            # Запускаем контейнеры приложения в фоновом режиме
            - docker-compose up