# Bitbucket Pipeline file

# This template allows you to validate your PHP application.
# The workflow allows running tests and code linting on the default branch.

pipelines:
  default:
    - step:
        name: Build
        script:
          - echo "Build an image with current project via docker"

          # Проверяем что находимся на ветке docker-release
          - if [ "${BITBUCKET_PR_DESTINATION_BRANCH}" = "docker-release" ];

          # Запускаем контейнеры приложения в фоновом режиме
          - docker-compose up -d