# Bitbucket Pipeline file

# This template allows you to validate your PHP application.
# The workflow allows running tests and code linting on the default branch.

pipelines:
  branches:
    docker-release:
      - step:
          name: Install docker-compose on bitbucket
          image: python:3.8.1
          services:
            - docker
          caches:
            - docker
            - pip
          script:
            - pip install docker-compose
      - step:
          name: Build
          script:
            - echo "Build an image with current project via docker"

            # Запускаем контейнеры приложения в фоновом режиме
            - docker-compose up