# Bitbucket Pipeline file

# This template allows you to validate your PHP application.
# The workflow allows running tests and code linting on the default branch.

image: docker:stable

options:
  docker: true

pipelines:
  branches:
    docker-release:
      - step:
          name: Build
          script:
            - dependencies.sh
            - echo "Build an image with current project via docker"

            # Запускаем контейнеры приложения в фоновом режиме
            - docker-compose up