# Bitbucket Pipeline file

# This template allows you to validate your PHP application.
# The workflow allows running tests and code linting on the default branch.
image: docker:stable

options:
  docker: true

pipelines:
  branches:
    docker-release:
      - step:
          name: Build
          runs-on:
            - self.hosted
            - linux
          script:
            # Экспоритруем переменные зашитые в битбакет для разветки
            - echo DB_NAME=$DB_NAME > .env
            - echo DB_USER=$DB_USER >> .env
            - echo DB_PASSWORD=$DB_PASSWORD >> .env

            - echo "Собираем Docker контейнеры"

            # Запускаем контейнеры приложения в фоновом режиме
            - sudo docker-compose up -d

            - echo "Обновляем зависимости composer"

            # Обновляем зависимости композера
            - sudo docker-compose exec -T app composer install --no-interaction