# Bitbucket Pipeline file

# This template allows you to validate your PHP application.
# The workflow allows running tests and code linting on the default branch.

image: docker:stable

options:
  docker: true

pipelines:
  branches:
    docker-release:
      - step:
          name: Install Python and docker
          script:
            - set -eu

            # Add python pip and bash
            - apk add --no-cache py-pip bash

            - pip3 install --upgrade pip setuptools

            # Install docker-compose via pip
            - pip install --no-cache-dir docker-compose
            - docker-compose -v
      - step:
          name: Build
          script:
            - echo "Build an image with current project via docker"

            # Запускаем контейнеры приложения в фоновом режиме
            - docker-compose up