# Bitbucket Pipeline file

# This template allows you to validate your PHP application.
# The workflow allows running tests and code linting on the default branch.

  pipelines:
    default:
      - step:
        name: Build
        script:
         # Запускаем контейнеры приложения в фоновом режиме
          - docker-compose up -d