# Bitbucket Pipeline file

# This template allows you to validate your PHP application.
# The workflow allows running tests and code linting on the default branch.

image: docker:stable

options:
  docker: true

pipelines:
  branches:
    docker-release:
      - step:
          name: Install Python and docker
          script:
            - install python-setuptools
            - install libxml2-devel libxslt-devel libyaml-devel
            - curl -skS https://bootstrap.pypa.io/get-pip.py | python
            - pip install virtualenv
            - curl -skS https://raw.githubusercontent.com/mitsuhiko/pipsi/master/get-pipsi.py | python
            - pip install docker-compose
            - docker-compose -v
      - step:
          name: Build
          script:
            - echo "Build an image with current project via docker"

            # Запускаем контейнеры приложения в фоновом режиме
            - docker-compose up