name: Clear Cache on Merge

on:
  pull_request:
    types: [closed]
    branches:
      - dev
      - master

jobs:
  clear-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Clear GitHub Actions Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache
            ~/.npm
            ~/.composer
            ~/.yarn
          key: ${{ github.repository }}-${{ github.event.pull_request.head.ref }}
          restore-keys: |
          fail-on-cache-miss: false