name: Deploy on Prod

# Настройка автодеплоя

on:
  push:
    branches:
      - "master"
#    types:
#      - closed

jobs:
  Deploy:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Deploy on Prod
      shell: bash
      env:
        SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
        SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
        SSH_USER: ${{secrets.SSH_USER}}
        SSH_KEY_PATH: ${{ github.workspace }}/../private.key
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_PRIVATE_KEY" > ../private.key
        sudo chmod 600 ../private.key
        echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        ssh -i "$SSH_KEY_PATH" "$SSH_USER"@wiki-tarkov.ru 'cd /var/www/wiki-tarkov/html && git pull origin-github master'

