name: Deploy on Prod

# Настройка автодеплоя

on:
  push:
    branches:
      - "master"
#    types:
#      - closed

jobs:
  Deploy:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Deploy on Prod
      shell: bash
      env:
        SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
        SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
        SSH_USER: ${{secrets.SSH_USER}}
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        ssh-keyscan wiki-tarkov.ru >> /home/runner/.ssh/known_hosts
        ssh -i ~/.ssh/id_rsa "$SSH_USER"@wiki-tarkov.ru 'cd /var/www/wiki-tarkov/html && git pull origin-github master'