name: Deploy on Prod

# Автодеплой на PROD - Только ветка Master, только при удачных мержах
on:
  pull_request:
    branches:
      - "master"
    types:
      - closed

jobs:
  Deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Deploy on Prod
      shell: bash
      env:
        SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
        SSH_USER: ${{secrets.SSH_USER}}
      run: |
        echo "Cancelled"
        echo "Deploy on PROD disabled for now"