name: GitHub Actions

on:
  pull_request:
    branches:
      - "master"
      - "dev"

# Существующие задачи 
jobs:
  # Прогоняем проект на поиск уязвимостей - Snyk
  snyk-security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/php@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  # Собираем проект и прогоняем тестами
  Tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      
      # Настройка Docker и кеширования
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Install Docker and Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      # Кеширование Composer
      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: vendor/
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      # Настройка переменных окружения
      - name: Set up environment variables
        env:
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          DB_DSN: ${{ secrets.DB_DSN }}
          DB_TEST_DSN: ${{ secrets.DB_TEST_DSN }}
          DB_TEST_CHARSET: ${{ secrets.DB_TEST_CHARSET }}
          DB_CHARSET: ${{ secrets.DB_CHARSET }}
          DOMAIN: ${{ secrets.DOMAIN }}
          DOMAIN_PROTOCOL: ${{ secrets.DOMAIN_PROTOCOL }}
          DB_TEST_NAME: ${{ secrets.DB_TEST_NAME }}
          DB_TEST_USER: ${{ secrets.DB_TEST_USER }}
          DB_TEST_PASSWORD: ${{ secrets.DB_TEST_PASSWORD }}
        run: |
          cat << EOF > .env
          DB_NAME="$DB_NAME"
          DB_USER="$DB_USER"
          DB_PASSWORD="$DB_PASSWORD"
          REDIS_HOST="$REDIS_HOST"
          DB_DSN="$DB_DSN"
          DB_TEST_DSN="$DB_TEST_DSN"
          DB_TEST_CHARSET="$DB_TEST_CHARSET"
          DB_CHARSET="$DB_CHARSET"
          DOMAIN="$DOMAIN"
          DOMAIN_PROTOCOL="$DOMAIN_PROTOCOL"
          DB_TEST_NAME="$DB_TEST_NAME"
          DB_TEST_USER="$DB_TEST_USER"
          DB_TEST_PASSWORD="$DB_TEST_PASSWORD"
          DEBUG_STATUS=true
          ENVIRONMENT=dev
          EOF

      # Сборка и запуск контейнеров
      - name: Build containers
        run: docker-compose build --cache-from type=local,src=/tmp/.buildx-cache --cache-to type=local,dest=/tmp/.buildx-cache-new

      - name: Start containers
        run: docker-compose up -d

      # Установка зависимостей
      - name: Install Composer dependencies
        run: docker-compose exec -T app composer install --no-interaction --prefer-dist --optimize-autoloader

      # Настройка базы данных
      - name: Configure database
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          docker exec -t tarkov_db mysql -u root -p"$DB_PASSWORD" --execute "
            CREATE DATABASE IF NOT EXISTS test_migrations_db;
            GRANT SUPER ON *.* to 'prod_user'@'%' WITH GRANT OPTION;
            GRANT ALL PRIVILEGES ON dev_eft.* to 'prod_user'@'%' WITH GRANT OPTION;
            GRANT ALL PRIVILEGES ON test_migrations_db.* to 'prod_user'@'%' WITH GRANT OPTION;"

      # Применение миграций
      - name: Run migrations
        run: |
          docker-compose exec -T app php yii migrate --interactive=0
          docker-compose exec -T app php yii migrate --db db_test --interactive=0

      # Очистка кеша
      - name: Clear Redis cache
        run: docker-compose exec -T redis redis-cli flushall

      # Запуск тестов
      - name: Run tests
        run: docker-compose exec -T app vendor/bin/codecept run

      # Сохранение кеша докера
      - name: Save Docker cache
        run: |
          mkdir -p /tmp/.buildx-cache-new
          if [ -d "/tmp/.buildx-cache" ]; then
            rm -rf /tmp/.buildx-cache
          fi
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache